language: ruby
sudo: false
rvm:
  # - 2.4.2
  - 2.2.0

before_install:
  # - install terraform
  - ruby -v
  - env
  - echo "${AWS_ACCESS_KEY_ID}"
  - which rvm
  - rvm list
  - echo "before install"

install:
  - which gem
  - gem -v
  - gem install bundler --no-rdoc --no-ri
  - bundle install

before_script:
  - uname -a
  - which apt
  - which yum
  - docker run -i -t hashicorp/terraform:light fmt -check=true; if [ $? -ne 0 ]; exit 1; fi
  - wget
  - terraform fmt -check=true; if [ $? -ne 0 ]; exit 1; fi
  - terraform validate
  - echo 'before script'

script:
  - kitchen test --destroy always

# after_success:
#   - echo 'foo'

# after_failure:
#   - echo 'foo'

before_deploy:
# create new release in github? check if this is new release?
  - echo 'before_deploy phase'

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: dev

# after_deploy:
#   - echo 'foo'

# after_script:
#   - echo 'foo'
